### ISSUE TITLE
[Task]: Add Shimmer Java Code Examples

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota.rs#1389]
### Task description

As we aim to make developer onboarding easy in all languages, it'd be great to provide the same examples in all languages.  

### Requirements

Add examples showcasing the following functionalities using the Java binding:

- [ ] Get Address Balance
- [ ] Send a transaction
- [ ] Listen to MQTT

### Acceptance criteria

- [ ] The examples have been added to the binding 
- [ ] The examples have been added to the doc's how-to guides

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
